// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BookmarksColumns holds the columns for the "bookmarks" table.
	BookmarksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "bookmarks", Type: field.TypeString},
		{Name: "version", Type: field.TypeString, Default: "2.0.0"},
		{Name: "created", Type: field.TypeTime},
		{Name: "last_updated", Type: field.TypeTime},
		{Name: "deleted", Type: field.TypeTime, Nullable: true},
	}
	// BookmarksTable holds the schema information for the "bookmarks" table.
	BookmarksTable = &schema.Table{
		Name:       "bookmarks",
		Columns:    BookmarksColumns,
		PrimaryKey: []*schema.Column{BookmarksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BookmarksTable,
	}
)

func init() {
}
