// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mrusme/xbsapi/ent/bookmark"
)

// BookmarkCreate is the builder for creating a Bookmark entity.
type BookmarkCreate struct {
	config
	mutation *BookmarkMutation
	hooks    []Hook
}

// SetBookmarks sets the "bookmarks" field.
func (bc *BookmarkCreate) SetBookmarks(s string) *BookmarkCreate {
	bc.mutation.SetBookmarks(s)
	return bc
}

// SetVersion sets the "version" field.
func (bc *BookmarkCreate) SetVersion(s string) *BookmarkCreate {
	bc.mutation.SetVersion(s)
	return bc
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (bc *BookmarkCreate) SetNillableVersion(s *string) *BookmarkCreate {
	if s != nil {
		bc.SetVersion(*s)
	}
	return bc
}

// SetCreated sets the "created" field.
func (bc *BookmarkCreate) SetCreated(t time.Time) *BookmarkCreate {
	bc.mutation.SetCreated(t)
	return bc
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (bc *BookmarkCreate) SetNillableCreated(t *time.Time) *BookmarkCreate {
	if t != nil {
		bc.SetCreated(*t)
	}
	return bc
}

// SetLastUpdated sets the "lastUpdated" field.
func (bc *BookmarkCreate) SetLastUpdated(t time.Time) *BookmarkCreate {
	bc.mutation.SetLastUpdated(t)
	return bc
}

// SetNillableLastUpdated sets the "lastUpdated" field if the given value is not nil.
func (bc *BookmarkCreate) SetNillableLastUpdated(t *time.Time) *BookmarkCreate {
	if t != nil {
		bc.SetLastUpdated(*t)
	}
	return bc
}

// SetDeleted sets the "deleted" field.
func (bc *BookmarkCreate) SetDeleted(t time.Time) *BookmarkCreate {
	bc.mutation.SetDeleted(t)
	return bc
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (bc *BookmarkCreate) SetNillableDeleted(t *time.Time) *BookmarkCreate {
	if t != nil {
		bc.SetDeleted(*t)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BookmarkCreate) SetID(u uuid.UUID) *BookmarkCreate {
	bc.mutation.SetID(u)
	return bc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (bc *BookmarkCreate) SetNillableID(u *uuid.UUID) *BookmarkCreate {
	if u != nil {
		bc.SetID(*u)
	}
	return bc
}

// Mutation returns the BookmarkMutation object of the builder.
func (bc *BookmarkCreate) Mutation() *BookmarkMutation {
	return bc.mutation
}

// Save creates the Bookmark in the database.
func (bc *BookmarkCreate) Save(ctx context.Context) (*Bookmark, error) {
	var (
		err  error
		node *Bookmark
	)
	bc.defaults()
	if len(bc.hooks) == 0 {
		if err = bc.check(); err != nil {
			return nil, err
		}
		node, err = bc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookmarkMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = bc.check(); err != nil {
				return nil, err
			}
			bc.mutation = mutation
			if node, err = bc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(bc.hooks) - 1; i >= 0; i-- {
			if bc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, bc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Bookmark)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from BookmarkMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BookmarkCreate) SaveX(ctx context.Context) *Bookmark {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BookmarkCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BookmarkCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BookmarkCreate) defaults() {
	if _, ok := bc.mutation.Version(); !ok {
		v := bookmark.DefaultVersion
		bc.mutation.SetVersion(v)
	}
	if _, ok := bc.mutation.Created(); !ok {
		v := bookmark.DefaultCreated()
		bc.mutation.SetCreated(v)
	}
	if _, ok := bc.mutation.LastUpdated(); !ok {
		v := bookmark.DefaultLastUpdated()
		bc.mutation.SetLastUpdated(v)
	}
	if _, ok := bc.mutation.ID(); !ok {
		v := bookmark.DefaultID()
		bc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BookmarkCreate) check() error {
	if _, ok := bc.mutation.Bookmarks(); !ok {
		return &ValidationError{Name: "bookmarks", err: errors.New(`ent: missing required field "Bookmark.bookmarks"`)}
	}
	if _, ok := bc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Bookmark.version"`)}
	}
	if v, ok := bc.mutation.Version(); ok {
		if err := bookmark.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Bookmark.version": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "Bookmark.created"`)}
	}
	if _, ok := bc.mutation.LastUpdated(); !ok {
		return &ValidationError{Name: "lastUpdated", err: errors.New(`ent: missing required field "Bookmark.lastUpdated"`)}
	}
	return nil
}

func (bc *BookmarkCreate) sqlSave(ctx context.Context) (*Bookmark, error) {
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (bc *BookmarkCreate) createSpec() (*Bookmark, *sqlgraph.CreateSpec) {
	var (
		_node = &Bookmark{config: bc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: bookmark.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: bookmark.FieldID,
			},
		}
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := bc.mutation.Bookmarks(); ok {
		_spec.SetField(bookmark.FieldBookmarks, field.TypeString, value)
		_node.Bookmarks = value
	}
	if value, ok := bc.mutation.Version(); ok {
		_spec.SetField(bookmark.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := bc.mutation.Created(); ok {
		_spec.SetField(bookmark.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := bc.mutation.LastUpdated(); ok {
		_spec.SetField(bookmark.FieldLastUpdated, field.TypeTime, value)
		_node.LastUpdated = value
	}
	if value, ok := bc.mutation.Deleted(); ok {
		_spec.SetField(bookmark.FieldDeleted, field.TypeTime, value)
		_node.Deleted = &value
	}
	return _node, _spec
}

// BookmarkCreateBulk is the builder for creating many Bookmark entities in bulk.
type BookmarkCreateBulk struct {
	config
	builders []*BookmarkCreate
}

// Save creates the Bookmark entities in the database.
func (bcb *BookmarkCreateBulk) Save(ctx context.Context) ([]*Bookmark, error) {
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Bookmark, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BookmarkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BookmarkCreateBulk) SaveX(ctx context.Context) []*Bookmark {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BookmarkCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BookmarkCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
